#!/usr/bin/env python3
"""Generate a PS3 (webMAN PS3MAPI) deploy script from word lists.

Usage: gen_deploy.py <out.sh> <title> <words.txt> [<words.txt> ...]
Word list lines: '0xADDR ORIG NEW' (cave words have ORIG 00000000).  The script offers
apply | off | verify, reads the PID from home.ps3mapi and pokes with setmem.ps3mapi.
Hook words (branches into caves) are applied LAST and removed FIRST so the caves are always
complete while a hook is live."""
import sys

out, title, files = sys.argv[1], sys.argv[2], sys.argv[3:]
words = []
for f in files:
    for line in open(f):
        p = line.split()
        if len(p) == 3:
            words.append((int(p[0], 16), int(p[1], 16), int(p[2], 16)))
        elif len(p) == 2:
            words.append((int(p[0], 16), 0, int(p[1], 16)))
seen = {}
for a, o, n in words:
    assert a not in seen or seen[a] == (o, n), f'conflicting words at {a:#x}'
    seen[a] = (o, n)
words = sorted(seen.items())
caves = [(a, o, n) for a, (o, n) in words if o == 0]
code = [(a, o, n) for a, (o, n) in words if o != 0]

def table(ws):
    return '\n'.join(f'0x{a:08x} {o:08X} {n:08X}' for a, o, n in ws)

script = f'''#!/bin/bash
# {title}
# Generated by tools/gen_deploy.py from: {' '.join(files)}
#   PS3=192.168.1.11 {out.split('/')[-1]} apply | off | verify
# Code pokes only take effect when set COLD in the main menu (instruction cache):
# start GT5, stay in the main menu, run 'apply', then Arcade -> 2P Split Screen -> player 3 = yes.
: "${{PS3:?set PS3=<console ip>}}"
PID=$(curl -s --max-time 10 "http://$PS3/home.ps3mapi" | grep -oiE 'proc=0x[0-9a-f]+' | head -1 | cut -d= -f2)
[ -n "$PID" ] || {{ echo "no game process found"; exit 1; }}
echo "pid=$PID"
poke() {{ curl -s --max-time 20 "http://$PS3/setmem.ps3mapi?proc=$PID&addr=$1&val=$2" >/dev/null; }}
rd()   {{ curl -s --max-time 20 "http://$PS3/getmem.ps3mapi?proc=$PID&addr=$1&len=4" | grep -oiE '\\b[0-9A-F]{{2}} [0-9A-F]{{2}} [0-9A-F]{{2}} [0-9A-F]{{2}}\\b' | head -1 | tr -d ' '; }}
CAVES='
{table(caves)}
'
CODE='
{table(code)}
'
MODE="${{1:-verify}}"
case "$MODE" in
  apply)
    echo "$CAVES" | while read -r a o n; do [ -z "$a" ] && continue; poke "$a" "$n"; done
    echo "$CODE"  | while read -r a o n; do [ -z "$a" ] && continue; poke "$a" "$n"; done
    echo "applied {len(caves)} cave words + {len(code)} code words"; "$0" verify ;;
  off)
    echo "$CODE"  | while read -r a o n; do [ -z "$a" ] && continue; poke "$a" "$o"; done
    echo "$CAVES" | while read -r a o n; do [ -z "$a" ] && continue; poke "$a" "$o"; done
    echo "restored originals" ;;
  verify)
    bad=0; on=0; off=0
    while read -r a o n; do
        [ -z "$a" ] && continue
        v=$(rd "$a"); v=${{v^^}}
        if [ "$v" = "$n" ]; then on=$((on+1)); elif [ "$v" = "$o" ]; then off=$((off+1)); else bad=$((bad+1)); echo "  $a = $v (neither $o nor $n)"; fi
    done <<< "$CAVES
$CODE"
    echo "patched=$on original=$off unexpected=$bad" ;;
  *) echo "usage: $0 apply|off|verify"; exit 1 ;;
esac
'''
open(out, 'w').write(script)
import os; os.chmod(out, 0o755)
print(f'{out}: {len(caves)} cave words, {len(code)} code words')
